#    filters:
#      tags:
#        only: /^v.*/

version: 2
jobs:
  build:
    working_directory: ~/swanco
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

#      - run:
#          name: Update npm
#          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Compile distributive
          command: npm run build

      - run:
          name: Build API documentation
          command: npm run doc
      - store_artifacts:
          path: doc
          destination: doc

      - run:
          name: Execute linter
          command: npm run lint -- --format junit --output-file ./reports/eslint.xml
      - store_test_results:
          path: ./reports/

      - run:
          name: Execute tests
          command: npm run test -- --ci --runInBand --reporters jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
      - store_test_results:
          path: ./reports/
      - store_artifacts:
          path: coverage
          destination: coverage
