version: 2
jobs:
  build:
    filters:
      tags:
        only: /^v.*/
    working_directory: ~/swanco
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Execute tests
          command: npm test
      - run:
          name: Build API documentation
          command: npm run doc
      - store_artifacts:
          path: doc
          prefix: doc
      - store_test_results:
          path: junit.xml
